telegram:
  bot_token: TELEGRAM_BOT_TOKEN
  user_ids: [TELEGRAM_USER_ID_1, TELEGRAM_USER_ID_2 ... TELEGRAM_USER_ID_N]
claude:
  api: CLAUDE_API_KEY # leave it blank if you don't want to use claude
bard:
  api: BARD_API_KEY (__Secure-1PSID, __Secure-1PSIDTS) # leave it blank if you don't want to use bard
